version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: auth-sgbd
      MYSQL_USER: fslab
      MYSQL_PASSWORD: fslab
      MYSQL_ROOT_PASSWORD: fslab
    expose:
      - "3306"
    ports:
      - "3333:3306"
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: fslab@sgbd
    ports:
      - '8016:80'

volumes:
  data: